### ISSUE TITLE
Missing previous and next buttons

### ISSUE THREAD

**Issue by Vathanak7** [nimsandu/spicetify-bloom#30]
Spotify for Windows
1.1.87.612.gf8d110e2

https://i.imgur.com/PFquVym.png

**Comment by HuyHung1408** [comment]
![image](https://user-images.githubusercontent.com/86362423/174485649-756a329e-9857-4fbb-a136-e9d730f9c1ef.png)
Spotify 1.1.87, all fine

**Comment by nimsandu** [comment]
> Spotify for Windows 1.1.87.612.gf8d110e2
> 
> https://i.imgur.com/PFquVym.png
 you have to re install the latest version

**Comment by akashirai** [comment]
![image](https://user-images.githubusercontent.com/107809851/174494204-a262e1ad-4c0d-4154-a17c-b54fde53a1a3.png)

encountering the same issue after reinstalling (on latest spicetify version as well)

**Comment by HuyHung1408** [comment]
![image](https://user-images.githubusercontent.com/86362423/174516047-06fc1ea3-1a36-4071-8cb3-669a6ca13c58.png)

Make sure that bloom is the only theme in the config-xpui file. Other theme may cause the issue

**Comment by HuyHung1408** [comment]
![image](https://user-images.githubusercontent.com/86362423/174516865-d4b5915f-4276-4b08-a357-a43597c2d741.png)
Also bloom theme shows wrong icon for lyrics plus

**Comment by nimsandu** [comment]
im not talking about spicetify version @akashirai could you please delete the whole theme and re install it by following script
```powershell
Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/nimsandu/spicetify-bloom/main/install.ps1" | Invoke-Expression
```

**Comment by nimsandu** [comment]
????

**Comment by nimsandu** [comment]
Have you Deleted bloom theme folder completely?

**Comment by nimsandu** [comment]
We have fixed it in latest bloom-theme version

**Comment by HuyHung1408** [comment]
> Have you Deleted bloom theme folder completely?

yup I did

**Comment by Vathanak7** [comment]
> We have fixed it in latest bloom-theme version

Latest Spotify version on Windows 11. Reinstalled everything, still have the same problem.

https://i.imgur.com/x5BNIQg.png

**Comment by akashirai** [comment]
After doing some cross-reference and research, I noticed that the latest version of bloom was missing .main-SkipForwardButton and .main-skipBackButton. 

Note: This was done on Windows 10, latest spicetify version, and 1.1.87 for spotify. This resolved the issue for me, but I went into user.css for bloom, I entered the following code below .player-controls__buttons button {
  padding-left: 20px;
  padding-right: 20px;
}

```
.main-skipForwardButton-button {
  -webkit-mask-image: url('./fluentui-system-icons/ic_fluent_next_24_filled.svg');
  background-color: var(--spice-text) !important;
  height: 24px !important;
}

.main-skipBackButton-button {
  -webkit-mask-image: url('./fluentui-system-icons/ic_fluent_previous_24_filled.svg');
  background-color: var(--spice-text) !important; 
  height: 22px !important;
}
```
![image](https://user-images.githubusercontent.com/107809851/175666243-6c3761ac-f11b-4b7b-b4a9-a2ae02cf6eb6.png)

**Comment by nimsandu** [comment]
@akashirai i merged your humble fix

Thanx 
Im closing this issue
