### ISSUE TITLE
Titlebar is not being themed correctly

### ISSUE THREAD

**Issue by npxtune** [nimsandu/spicetify-bloom#345]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit), 1.2.36.959.g04bf500c
- Installed from: Spotify Site
- Spicetify version: Spicetify v2.36.10
- Color scheme: Dark
- Extensions: fluent.js
- Custom apps: n/a
- Bloom installation method: PowerShell script
```

### Description

1. Install Spotify (MS Store or Spotify Website)
2. Install spicetify and the theme

### Screenshots

![Screenshot 2024-05-05 205802](https://github.com/nimsandu/spicetify-bloom/assets/42376598/8c1d291f-d938-4a61-8363-32963f93b88a)

The titlebar is not being themed correctly, it's being covered halfway.

**Comment by BedBug2479** [comment]
![image](https://github.com/nimsandu/spicetify-bloom/assets/43089040/3ae08b83-6f12-43e2-8bb0-529575c98b7d)

Also adding to the above while sliding down in the playlist the PLAY/PAUSE button is displayed not correctly

**Comment by sanoojes** [comment]
https://github.com/nimsandu/spicetify-bloom/pull/342 multiple things fixed

**Comment by nimsandu** [comment]
@npxtune, the issue was fixed by a pull request from @sanoojes! could you please update bloom and confirm the fix? so we can close this issue

**Comment by BedBug2479** [comment]
> @npxtune, the issue was fixed by a pull request from @sanoojes! could you please update bloom and confirm the fix? so we can close this issue

Hi the title bar seems to be fixed now for me but not sure about @npxtune

**Comment by npxtune** [comment]
Updated Bloom and it's still happening, the buttons for the player are now broken as well.

![Screenshot 2024-05-11 103600](https://github.com/nimsandu/spicetify-bloom/assets/42376598/128c0feb-22db-4fd9-a6cc-7651fbb72ca4)

**Comment by sanoojes** [comment]
> Updated Bloom and it's still happening, the buttons for the player are now broken as well.
> 
> ![Screenshot 2024-05-11 103600](https://private-user-images.githubusercontent.com/42376598/329766971-128c0feb-22db-4fd9-a6cc-7651fbb72ca4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MjAzODMsIm5iZiI6MTcxNTQyMDA4MywicGF0aCI6Ii80MjM3NjU5OC8zMjk3NjY5NzEtMTI4YzBmZWItMjJkYi00ZmQ5LWE2Y2MtNzY1MWZiYjcyY2E0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA5MzQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0YWQwYzBmZjhkMzYzNzM5YmQ4OThmMzUwZTA4ODBhMmVkMmIwZDExMTc1MDIyZGYwNzY3NDIyNTFjNTE1NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b4vzOQRZDDvQwbeziMRpgTsyQLE1MremFcXZy0P5ZLM)

i think its not a problem from bloom

**Comment by sanoojes** [comment]
This should be the search bar for bloom 
![image](https://github.com/nimsandu/spicetify-bloom/assets/93819264/ab966cd5-0e83-48e2-b46a-e9c3c04325ec)

Home page
![image](https://github.com/nimsandu/spicetify-bloom/assets/93819264/6e707feb-658e-47a3-b360-de9815b55491)

**Comment by BedBug2479** [comment]
> Updated Bloom and it's still happening, the buttons for the player are now broken as well.
> 
> ![Screenshot 2024-05-11 103600](https://private-user-images.githubusercontent.com/42376598/329766971-128c0feb-22db-4fd9-a6cc-7651fbb72ca4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0Mjk0MjQsIm5iZiI6MTcxNTQyOTEyNCwicGF0aCI6Ii80MjM3NjU5OC8zMjk3NjY5NzEtMTI4YzBmZWItMjJkYi00ZmQ5LWE2Y2MtNzY1MWZiYjcyY2E0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDEyMDUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxODU2ZWVlN2MzMDFjYTJmYzc0ZThmNjg0NmI0NGI4ZTAyZWVkMTUzODA2Y2RlMDIyNzc2MTcxYTMxNmY1YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4bg1TNE2FtkkIkhWjXKJY8WAvt-tTtX91gKJgdfr5_4)

If you remove the *topsearchbar* option it is working f9

**Comment by sanoojes** [comment]
i tryed it out on a vm some of the updated spotify has search bar like that i will find a way to fix it

**Comment by sanoojes** [comment]
found out the issue last day. there is a toggle new global nav in experiments

**Comment by npxtune** [comment]
yup, seems to be caused by the navbar experiment (ffs spotify). Disabled it and it's gone now, thanks!

**Comment by EDM115** [comment]
PSA : the global navbar experiment can no longer be disabled, and as such the theme breaks on `1.2.46.462.gf57913e0`

**Comment by EDM115** [comment]
![image](https://github.com/user-attachments/assets/11e5ceb6-8f31-4688-a36f-6d4595301ccb)
- Top bar isn't shown
- icons are squished (but it's also like this without the theme)
- user profile and left buttons doesn't appear
- window buttons aren't themed
- Home and others from the left bar disappeared
- Top of the pages are hidden behind the top bar rendering them unusable

**Comment by sanoojes** [comment]
> PSA : the global navbar experiment can no longer be disabled, and as such the theme breaks on `1.2.46.462.gf57913e0`

yes global nav is default and the control nav is removed i will add a fix rn
