### ISSUE TITLE
Stretched Playlist when downloaded/downloading

### ISSUE THREAD

**Issue by LarveyOfficial** [nimsandu/spicetify-bloom#72]
This is the same as the first issue in #65

It was stated to be closed due to #71 but that only solves stretching during the playing state not the downloaded/downloading state
![179428110-e7391262-9915-4aca-ba0a-0e25b4b67b56](https://user-images.githubusercontent.com/39219859/180661810-f337ec89-ab09-4eb5-8a4e-9160ae4950a6.png)

**Comment by MGPlayzYT** [comment]
Whoops, I'll see if I can fix that as well.

**Comment by nimsandu** [comment]
@MGPlayzYT Check #49 issue and fix @Astromations fixed downloading status broken issue

**Comment by MGPlayzYT** [comment]
@nimsandu tried that fix, didn't work. the classes for the icon have changed, and I don't know how to force show it.

**Comment by MGPlayzYT** [comment]
Update: I found it (I think)
@LarveyOfficial try my fix in https://github.com/MGPlayzYT/spicetify-bloom/blob/main/user.css
let me know if it works or not.

**Comment by nimsandu** [comment]
@LarveyOfficial Can you figure it out?

**Comment by LarveyOfficial** [comment]
I haven't had the time to properly test it, it would probably be best for someone else to test the issue

**Comment by kyrie25** [comment]
Resolved via #82 @nimsandu

**Comment by nimsandu** [comment]
@kyrie25 All right

**Comment by LarveyOfficial** [comment]
mmm seems issue still happens with public playlists 
![image](https://user-images.githubusercontent.com/39219859/183717317-af0dd6f2-6059-40dc-8280-62e62170bb83.png)

**Comment by nimsandu** [comment]
@LarveyOfficial  can you open another issue mentioning public playlists
